#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import csv
import gzip
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "Crossword/data/crossword_catalog.tsv"
SOLUTIONS = ROOT / "Crossword/data/solution_words.txt"
SOURCES = ROOT / "Crossword/data/sources.json"
OUT = ROOT / "Shared/www/crossword-data.js"


def norm(s: str) -> str:
    repl = {
        "Ä": "AE", "Ö": "OE", "Ü": "UE", "ẞ": "SS", "ß": "SS",
        "ä": "AE", "ö": "OE", "ü": "UE",
    }
    s = "".join(repl.get(c, c) for c in s).upper()
    import unicodedata
    s = "".join(
        c for c in unicodedata.normalize("NFD", s)
        if unicodedata.category(c) != "Mn"
    )
    return re.sub(r"[^A-Z]", "", s)


def _normalized_source_bytes(path: Path) -> bytes:
    data = path.read_bytes()
    return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def source_digest() -> str:
    h = hashlib.sha256()
    h.update(_normalized_source_bytes(CATALOG))
    h.update(b"\0")
    h.update(_normalized_source_bytes(SOLUTIONS))
    h.update(b"\0")
    if SOURCES.exists():
        h.update(_normalized_source_bytes(SOURCES))
    return h.hexdigest()


def load_payload():
    entries = []
    seen = set()

    with CATALOG.open(encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        required = {"answer", "clue", "category", "language", "difficulty", "source"}
        if not required.issubset(reader.fieldnames or []):
            raise SystemExit(
                f"Katalogspalten fehlen: {required - set(reader.fieldnames or [])}"
            )

        for row in reader:
            answer = norm(row["answer"])
            clue = " ".join(row["clue"].split())
            if not 2 <= len(answer) <= 30 or not clue:
                continue

            key = (answer, clue.casefold())
            if key in seen:
                continue
            seen.add(key)

            entries.append({
                "a": answer,
                "q": clue,
                "c": row.get("category", "allgemein") or "allgemein",
                "l": row.get("language", "de") or "de",
                "d": max(1, min(5, int(row.get("difficulty") or 2))),
                "s": row.get("source", ""),
            })

    solutions = []
    seen_sol = set()
    for line in SOLUTIONS.read_text(encoding="utf-8").splitlines():
        word = norm(line.strip())
        if 10 <= len(word) <= 20 and word not in seen_sol:
            seen_sol.add(word)
            solutions.append(word)

    if len(entries) < 200:
        raise SystemExit("Katalog zu klein (<200 Einträge).")
    if len(solutions) < 25:
        raise SystemExit("Zu wenige Lösungswörter (<25).")

    source_meta = (
        json.loads(SOURCES.read_text(encoding="utf-8"))
        if SOURCES.exists()
        else {}
    )
    return {
        "v": int(source_meta.get("catalog_version", 1)),
        "entries": entries,
        "solutions": solutions,
    }


def crypt(data: bytes) -> bytes:
    # Reversible build-time obfuscation, intentionally no claim of
    # cryptographic secrecy.
    state = 0xC0FFEE42
    out = bytearray(len(data))

    for i, b in enumerate(data):
        state ^= (state << 13) & 0xFFFFFFFF
        state ^= (state >> 17) & 0xFFFFFFFF
        state ^= (state << 5) & 0xFFFFFFFF
        state &= 0xFFFFFFFF
        out[i] = b ^ (state & 0xFF) ^ ((i * 31 + 0x5A) & 0xFF)

    return bytes(out)


def render(payload) -> str:
    raw = json.dumps(
        payload,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=False,
    ).encode("utf-8")

    # The compressed byte stream can vary between Python/zlib platforms.
    # Therefore --check validates the embedded source hash and the decoded
    # semantic payload instead of comparing the compressed bytes verbatim.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)
    encoded = base64.b64encode(crypt(packed)).decode("ascii")

    return (
        "// Generated by Deployment/Tools/build_crossword_data.py – DO NOT EDIT.\n"
        f"// source-sha256: {source_digest()}\n"
        f'window.__HAUCKI_CROSSWORD_DATA="HCW1:{encoded}";\n'
    )


def read_generated_payload(text: str):
    digest_match = re.search(
        r"(?m)^// source-sha256: ([0-9a-f]{64})\s*$",
        text,
    )
    data_match = re.search(
        r'window\.__HAUCKI_CROSSWORD_DATA="HCW1:([A-Za-z0-9+/=]+)";',
        text,
    )

    if not digest_match or not data_match:
        raise ValueError("Header oder HCW1-Datenblock fehlt.")

    encrypted = base64.b64decode(data_match.group(1), validate=True)
    packed = crypt(encrypted)
    raw = gzip.decompress(packed)
    payload = json.loads(raw.decode("utf-8"))

    return digest_match.group(1), payload


def check_output(expected_payload) -> tuple[bool, str]:
    if not OUT.exists():
        return False, "crossword-data.js fehlt."

    try:
        embedded_digest, embedded_payload = read_generated_payload(
            OUT.read_text(encoding="utf-8")
        )
    except Exception as exc:
        return False, f"crossword-data.js ist nicht lesbar/gültig: {exc}"

    expected_digest = source_digest()
    if embedded_digest != expected_digest:
        return (
            False,
            "crossword-data.js hat einen veralteten Quellhash "
            f"({embedded_digest} != {expected_digest}).",
        )

    if embedded_payload != expected_payload:
        return (
            False,
            "crossword-data.js enthält nicht den aktuellen semantischen Datenbestand.",
        )

    return True, ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated file is missing or semantically stale.",
    )
    args = ap.parse_args()

    payload = load_payload()

    if args.check:
        ok, reason = check_output(payload)
        if not ok:
            print(
                reason + " build_crossword_data.py ausführen.",
                file=__import__("sys").stderr,
            )
            return 1

        print(
            "Kreuzworträtsel-Daten OK: "
            f'{len(payload["entries"])} Fragen, '
            f'{len(payload["solutions"])} Lösungswörter.'
        )
        return 0

    text = render(payload)
    OUT.write_text(text, encoding="utf-8", newline="\n")

    print(f"Erzeugt: {OUT.relative_to(ROOT)}")
    print(
        f'{len(payload["entries"])} Fragen, '
        f'{len(payload["solutions"])} Lösungswörter, '
        f"{OUT.stat().st_size} Bytes gepackt."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
